language: python

python:

  - "3.6"

services:
  - postgresql

install:
# install packages
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database ah_alpha_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
# running tests
  - coverage run --source=. manage.py test
  - coverage report

after_success:
# send coverage to coveralls
  - coveralls
