# Generated by Django 2.1.4 on 2019-01-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='First_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='Second_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
