# Generated by Django 2.1.4 on 2019-01-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190125_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Second_name',
            new_name='Last_name',
        ),
    ]
